---

apiVersion: ashoksrirama.com/v1alpha1
kind: ClusterClaim
metadata:
  name: team-b-eks
  labels:
    cluster-owner: asramaa
spec:
  id: team-b-eks
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: large
    minNodeCount: 2
    region: us-west-2
    

---

apiVersion: ashoksrirama.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: team-b-gitops
  labels:
    cluster-owner: asramaa
spec:
  id: team-b-gitops
  compositionSelector:
    matchLabels:
      provider: argo
  parameters:
    kubeConfig:
      secretName: team-b-eks-cluster
      secretNamespace: crossplane-system
    gitOpsRepo: https://github.com/ashoksrirama/devops-toolkit-crossplane.git
