---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a-eks
  labels:
    cluster-owner: asramaa
spec:
  id: team-a-eks
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 2

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: team-a-gitops
  labels:
    cluster-owner: asramaa
spec:
  id: team-a-gitops
  compositionSelector:
    matchLabels:
      provider: argo
  parameters:
    kubeConfig:
      secretName: team-a-eks-cluster
      secretNamespace: crossplane-system
    gitOpsRepo: https://github.com/ashoksrirama/devops-toolkit-crossplane.git
